services:
  todoapp:
    container_name: todoapp
    image: node-typescript
    build:
      context: ./todoApi
    depends_on:
      - postgres
    environment:
      - API_HOST=todoapp
      - PORT=80
    ports:
      - "3000:80"
    volumes:
      # - .:/app
      - ./todoApi/src:/app/src
      - ./todoApi/__tests__:/app/__tests__
  postgres:
    container_name: postgres
    image: postgres:16.1
    environment:
      - POSTGRES_USER=allocation
      - POSTGRES_PASSWORD=abc123
    ports:
      - "54321:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: